### ISSUE TITLE
How to use the flag '-modified' in fillstruct? Could you give me a example?

### ISSUE THREAD

**Issue by mafulong** [davidrjenni/reftools#47]
-modified: read an archive of modified files from stdin

**Comment by davidrjenni** [comment]
If you call `fillstruct` with the `-modified` flag, instead of reading a file from disk, it reads in an "archive" from `stdin`. This is helpful for editors to use the tool with files which have changed and are not yet written to disk.

You can read more about the archive format here:
- https://arslan.io/2017/09/14/the-ultimate-guide-to-writing-a-go-tool/
- https://pkg.go.dev/golang.org/x/tools/go/buildutil?tab=doc#ParseOverlayArchive

And you can use it from the command line like this:

```
$ echo "package main" > foo.go
$ fillstruct -file=foo.go -line=9 -modified <<EOF
foo.go
121
package main

type user struct {
        firstName string
        lastName  string
}

func main() {
        _ = user{}
}
EOF
```

It will output:

```
[{"start":112,"end":118,"code":"user{\n\tfirstName: \"\",\n\tlastName:  \"\",\n}"}]
```

**Comment by mafulong** [comment]
> If you call `fillstruct` with the `-modified` flag, instead of reading a file from disk, it reads in an "archive" from `stdin`. This is helpful for editors to use the tool with files which have changed and are not yet written to disk.
> 
> You can read more about the archive format here:
> 
> * https://arslan.io/2017/09/14/the-ultimate-guide-to-writing-a-go-tool/
> * https://pkg.go.dev/golang.org/x/tools/go/buildutil?tab=doc#ParseOverlayArchive
> 
> And you can use it from the command line like this:
> 
> ```
> $ echo "package main" > foo.go
> $ fillstruct -file=foo.go -line=9 -modified <<EOF
> foo.go
> 121
> package main
> 
> type user struct {
>         firstName string
>         lastName  string
> }
> 
> func main() {
>         _ = user{}
> }
> EOF
> ```
> 
> It will output:
> 
> ```
> [{"start":112,"end":118,"code":"user{\n\tfirstName: \"\",\n\tlastName:  \"\",\n}"}]
> ```

thanks
